// UI Constants
export const UI_CONSTANTS = {
  TOAST_DURATION_MS: 4000,
  SUCCESS_MESSAGE_DURATION_MS: 3000,
  LONG_SUCCESS_MESSAGE_DURATION_MS: 5000,
  POLLING_INTERVAL_MS: 5000,
  SCREENSHOT_POLL_INTERVAL_MS: 3000,
  MAX_ACTION_LOG_ENTRIES: 200,
  PERCENTAGE_MULTIPLIER: 100,
} as const;

export type UIConstants = typeof UI_CONSTANTS;
